"""Verify the portable contract and golden fixtures against a checked-in SHA-256 manifest."""
from __future__ import annotations

import argparse
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = "contract-manifest.txt"


def inventory(root: Path) -> dict[str, str]:
    paths = [*root.glob("src/main/java/com/otectus/arsnspells/contract/*.java"),
             *root.glob("src/test/resources/ans-contract-fixtures/*.json"),
             root / "src/test/java/com/otectus/arsnspells/contract/ContractFixtureTest.java"]
    if len(paths) < 20 or any(not path.is_file() for path in paths):
        raise ValueError(f"Incomplete contract tree: {root}")
    # Git may check text out as CRLF on Windows. Hash the canonical LF source,
    # never a platform-specific working-tree line ending.
    return {path.relative_to(root).as_posix(): hashlib.sha256(
        path.read_bytes().replace(b"\r\n", b"\n")).hexdigest() for path in sorted(paths)}


def read_manifest(root: Path) -> dict[str, str]:
    return dict((line.split("  ", 1)[1], line.split("  ", 1)[0])
                for line in (root / MANIFEST).read_text(encoding="utf-8").splitlines()
                if line and not line.startswith("#"))


def write_manifest(root: Path, actual: dict[str, str]) -> None:
    (root / MANIFEST).write_text(
        "# Shared Java domain contracts and golden fixtures; SHA-256 over canonical LF text.\n"
        "# Generated by python tools/contract_parity.py --write.\n\n"
        + "".join(f"{digest}  {path}\n" for path, digest in sorted(actual.items())), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--other", type=Path, help="Other loader checkout; compare semantics before updating either manifest")
    parser.add_argument("--write", action="store_true", help="Record current contract after review")
    args = parser.parse_args()
    try:
        actual = inventory(ROOT)
        roots = [ROOT]
        if args.other:
            other = args.other.resolve()
            theirs = inventory(other)
            if actual != theirs:
                changed = sorted(path for path in actual.keys() | theirs.keys() if actual.get(path) != theirs.get(path))
                raise ValueError("Loader contract mismatch: " + ", ".join(changed))
            roots.append(other)
        for root in roots:
            if args.write:
                write_manifest(root, actual)
            elif read_manifest(root) != actual:
                raise ValueError(f"Contract manifest is stale in {root}; review the change and regenerate both manifests")
    except (OSError, ValueError) as error:
        parser.exit(1, f"FAIL: {error}\n")
    print(f"PASS: {len(actual)} contract sources/fixtures; {len(roots)} loader checkout(s)")


if __name__ == "__main__":
    main()
