#!/usr/bin/env python3
"""Generate versioned configuration/recipe references from the local loader checkout."""
from pathlib import Path
import argparse, hashlib, json, re
ROOT = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--version', default='3.3.0', help='Output documentation version')
reference_options = parser.parse_args()
if not re.fullmatch(r'[0-9]+(?:\.[0-9]+)*', reference_options.version): parser.error('Invalid version')
OUT = ROOT / 'docs' / reference_options.version
OUT.mkdir(parents=True, exist_ok=True)
CONFIG = ROOT / "src/main/java/com/otectus/arsnspells/config/AnsConfig.java"
source = CONFIG.read_text(encoding="utf-8")
java = list((ROOT / "src/main/java").rglob("*.java"))
tests = list((ROOT / "src/test/java").rglob("*.java")) + list((ROOT / "src/main/java/com/otectus/arsnspells/gametest").glob("*.java"))
texts = {p: p.read_text(encoding="utf-8") for p in set(java+tests)}
rows=[]
for match in re.finditer(r'(\w+)\s*=\s*BUILDER([\s\S]*?)\.define(?:InRange|ListAllowEmpty|List)?\(\s*"([^"\n]+)"\s*,', source):
    field, block, key = match.group(1,2,3)
    pos=match.end(); level=1; quoted=False; escaped=False; args=[]; start=pos
    while pos<len(source) and level:
        ch=source[pos]
        if quoted:
            if escaped: escaped=False
            elif ch=="\\": escaped=True
            elif ch=='"': quoted=False
        elif ch=='"': quoted=True
        elif ch in "([{": level+=1
        elif ch in ")]}":
            level-=1
            if level==0: args.append(source[start:pos].strip()); break
        elif ch=="," and level==1: args.append(source[start:pos].strip()); start=pos+1
        pos+=1
    section=[]
    for section_token in re.finditer(r'BUILDER\.(push|pop)\((?:"([^"\n]+)")?\)',source[:match.start()]):
        if section_token.group(1)=="push": section.append(section_token.group(2))
        elif section: section.pop()
    comments=[]
    for c in re.findall(r'"(?:\\.|[^"\\])*"',block):
        try: comments.append(json.loads(c))
        except ValueError: pass
    refs=[p.relative_to(ROOT).as_posix() for p in java if p!=CONFIG and re.search(r"\b"+field+r"\b",texts[p])]
    if len(re.findall(r"\b"+field+r"\b",source)) > 2:
        refs.append(CONFIG.relative_to(ROOT).as_posix()+" (internal accessor or migration)")
    direct_tests=[p.relative_to(ROOT).as_posix() for p in tests if re.search(r"\b"+field+r"\b",texts[p])]
    rows.append(dict(key=".".join(section+[key]),field=field,default=args[0],arguments=args[1:],description=" ".join(comments),runtime_references=sorted(refs),direct_test_references=sorted(direct_tests)))
manifest={"source":CONFIG.relative_to(ROOT).as_posix(),"sha256":hashlib.sha256(source.encode()).hexdigest(),"entries":rows}
(OUT/"config-reference.json").write_text(json.dumps(manifest,indent=2,ensure_ascii=False)+"\n",encoding="utf-8")
lines=[f"# {reference_options.version} configuration reference","","Generated by `tools/generate_release_references.py` from this checkout. Defaults and bounds are source declarations. Runtime references identify consumers; test references identify direct symbol references, not proof that every value or mod combination has run. A missing direct test reference is explicitly unverified by this inventory. Read the release evidence before shipping a pack.","",f"Source SHA-256: `{manifest['sha256']}`. {len(rows)} declared keys.",""]
for row in rows:
    lines += ["## `"+row["key"]+"`","",f"Default: `{row['default']}`. Declaration arguments after default: `{' ; '.join(row['arguments']) or 'none'}`.","",row["description"],"","Runtime readers: "+(", ".join("`"+x+"`" for x in row["runtime_references"]) or "none found outside configuration declaration; compatibility-only or inactive until verified")+".","","Direct test references: "+(", ".join("`"+x+"`" for x in row["direct_test_references"]) or "none found; behavior may be covered indirectly, not certified by this generator")+".",""]
(OUT/"config-reference.md").write_text("\n".join(lines),encoding="utf-8")
recipes=[]
for folder in [ROOT/"src/main/resources/data/ars_n_spells/recipes", ROOT/"src/main/resources/data/ars_n_spells/recipe"]:
    if folder.exists():
        for path in sorted(folder.rglob("*.json")):
            recipes.append((path.relative_to(ROOT).as_posix(),json.loads(path.read_text(encoding="utf-8"))))
lines=[f"# {reference_options.version} recipe reference","","Generated from every shipped ANS recipe in this loader checkout. Conditions and ingredients are shown verbatim; tag contents are resolved by the installed datapacks. A recipe ingredient is consumed when crafting that output, independently of whether the eventual ritual preserves its source book.","",f"{len(recipes)} recipe files.",""]
for name,data in recipes:
    lines += ["## `"+name+"`","","```json",json.dumps(data,ensure_ascii=False,indent=2),"```",""]
(OUT/"recipe-reference.md").write_text("\n".join(lines),encoding="utf-8")
print(f"Generated {len(rows)} config keys and {len(recipes)} recipes for {ROOT}")
